services:
  pgdb:
    image: postgres
    volumes:
      - sportserve-task-db-data:/var/lib/postgresql/data
    env_file:
      - env/.env.dev
    ports:
      - "5432:5432"
volumes:
  sportserve-task-db-data:
